version: '3'
services:
  php-fpm:
    # image: php:fpm-alpine
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on: 
      - database
  
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
    depends_on:
      - php-fpm
  
  database:
    image: mysql:8
    environment: 
      - MYSQL_DATABASE=phpdb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=qwer1234
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data-dir:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/data.sql